# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request: 
    types: [closed]

env:
  name: AZB
jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      name: Aung Zan Baw
    steps: 
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hello $name!
  pull_requests_only:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' 
      needs: [build]
      steps:
      - name: Run a one-line script
        run: echo Hello $name!
