# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request: 
    types: [closed]

env:
  name: AZB
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Run a multi-line script
      run: |
        echo Actor ${{ github.actor }}
        echo Committed by ${{ github.event.commits[0].author.name }}
  dump: 
    runs-on: [ubuntu-latest]
    env: 
      GITHUB_CONTEXT: ${{toJson(github)}} 
    steps:
      - run: echo "$GITHUB_CONTEXT"
  pull_requests_only:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' 
      needs: [build]
      steps:
      - name: Run a one-line script
        run: echo Hello $name!
  weather:
    runs-on: ubuntu-latest 
    env:
      location: '16.802934, 96.180069'
      lang: en
      units: us
      exclude: 'minutely, hourly, daily, alerts, flags'
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: Current Weather 
        run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret/$location?lang=lang&units=$units&exclude=$exclude
      
